issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:salekseev/helm-charts:ref:.*

permissions:
  contents: write
  metadata: read
  issues: write
  packages: write
  pull_requests: write

identities:
  release-please:
    permissions:
      contents: write
      pull_requests: write
      metadata: read

  chart-publisher:
    permissions:
      contents: read
      packages: write
      metadata: read
